services:
  auth-service:
    image: auth-service
    container_name: plotva-auth-service
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "8080:8080"
    volumes:
      - ../cfg/config.yml:/cfg/config.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
