services:
  user-service:
    image: user-service
    container_name: plotva-user-service
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_NAME
      - POSTGRES_PORT
      - S3_ENDPOINT
      - S3_ACCESS_KEY
      - S3_SECRET_KEY
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_NAME
      - S3_BUCKET=plotva
      - PYTHONPATH=.:src python user_service/main.py
    ports:
      - "9002:9002"
    extra_hosts:
      - "host.docker.internal:host-gateway"
