project_root: /home/pepelulka/mai/plotva.ru/

tasks:
  - service:
      compose_file_path: infra/postgres/postgres.docker-compose.yml # postgres
      req_env_vars:
        - POSTGRES_DB
        - POSTGRES_USER
        - POSTGRES_PASSWORD
  - service:
      compose_file_path: infra/kafka/kafka.docker-compose.yml # kafka
  - service:
      compose_file_path: infra/clickhouse/clickhouse.docker-compose.yml #clickhouse
      req_env_vars:
        - CLICKHOUSE_DB
        - CLICKHOUSE_USER
        - CLICKHOUSE_PASSWORD

