project_root: /home/pepelulka/mai/plotva.ru/

tasks:
  - service:
      compose_file_path: infra/postgres/postgres.docker-compose.yml # postgres
      req_env_vars:
        - POSTGRES_DB
        - POSTGRES_USER
        - POSTGRES_PASSWORD
  - service:
      compose_file_path: infra/monitoring/docker-compose.yml # monitoring
  - service:
      compose_file_path: user_service/docker-compose.yaml # user-service
      req_env_vars:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_HOST
        - POSTGRES_NAME
        - POSTGRES_PORT
        - S3_ENDPOINT
        - S3_ACCESS_KEY
        - S3_SECRET_KEY
        - DB_USER
        - DB_PASSWORD
        - DB_HOST
        - DB_NAME
      custom_build:
        command:
          dir: ./
          args: ["docker", "build", "-t", "user-service", "-f", "./user_service/Dockerfile", "."]
  - service:
      compose_file_path: auth-service/docker-compose.yaml # auth-service
      req_env_vars:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_DB
        - POSTGRES_HOST
        - POSTGRES_PORT
        - OLTP_ENDPOINT
      custom_build:
        command:
          dir: ./
          args: ["docker", "build", "-t", "auth-service", "-f", "./auth-service/Dockerfile", "."]
