services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    environment:
      - PROMETHEUS_CONFIG_NAME
    ports:
      - "9090:9090"
    volumes:
      - ./$PROMETHEUS_CONFIG_NAME:/etc/prometheus/win.prometheus.yml
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/win.prometheus.yml
volumes:
  prometheus_data:
    driver: local
